job/urls.py
from django.urls import include, path
from . import views
#name app for created
app_name='Job'

urlpatterns = [
    path('',views.job_list),
    path('<str:slug>',views.job_details, name="job_details"),
    
]

project/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('jobs/', include('job.urls',namespace='jobs')),
]
#     # ... the rest of your URLconf goes here ..
# urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
#     # ... the rest of your URLconf goes here ...

# urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from django.db import models

# Create your models here.

contact/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

job/models.py
from django.db import models
import uuid
import os
from django.utils.text import slugify
# # Create your models here.
'''django model field
    -html widget
    -validation 'email or not'
    -db size 'char, textor time ... best field for database'

'''



class Categorys(models.Model):
      name = models.CharField(max_length=20)

      def __str__(self):
        return self.name 
      

# set images in media file  by id  
def upload_image(instance, filename):
    imagename, extension = filename.split(".")
    return "jobs/%s.%s"%(instance.id , extension)

JOB_TYPE=(
    ('Full Time', 'Full time' ),
    ('Part Time', 'Part Time'),
)
class Job(models.Model):# jobs table 
    # id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title= models.CharField(max_length=30)# column
    # location
    job_type = models.CharField(max_length=50,choices=JOB_TYPE)
    descriptions= models.TextField(max_length=1000)
    published_add = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1)
    salary =  models.IntegerField(default=0)
    experiences = models.IntegerField(default=0)
    catagorys = models.ForeignKey(Categorys, on_delete=models.CASCADE)
    image = models.ImageField(upload_to = upload_image) 
    slug= models.SlugField(blank=True, null=True)

    
    def save (self, *args, **kwargs) :
        self.slug = slugify(self.title)
        super(Job, self).save(*args,**kwargs)   # 
    
    
    def __str__(self):
        return self.title

class User_apply_job(models.Model): 
    apply = models.ForeignKey(Job, related_name=("appl_job"), on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=50)
    email=models.EmailField( max_length=50)
    website = models.URLField()
    # cv = models.FileField( upload_to="cv/", max_length=100)
    coverletter = models.TextField(max_length=3000)
    create_at = models.DateField( auto_now=True)

    def __str__(self):
        return self.name

accounts/views.py
from django.shortcuts import render

# Create your views here.

blog/views.py
from django.shortcuts import render

# Create your views here.

contact/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render

# Create your views here.

job/views.py
from django.shortcuts import render
from .models import Job
from django.core.paginator import Paginator
from .form import ApplyJob 
# Create your views here.

def job_list(request):
    job_list=Job.objects.all()
    print("#####################################",job_list)
    # Show 1 contacts per page.
    paginator = Paginator(job_list, 1) 
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)  

    # context communicate with template 
    context ={
        "joblist": page_obj

    }

    return render(request, 'job/job_list.html',context ) 


def job_details(request, slug):
    only_job = Job.objects.get(slug=slug) # return get 1 response for job but return  filter multi jobs 
    print("###################################################",only_job)
    #if apply job post or get for sending in table 
    post_apply=request.method 
    if post_apply == "POST":
        # setting data in django model on table and checking and  saved 
        print('test1')
        form = ApplyJob(request.POST, request.FILES)
        if form.is_valid():
            print('test2')
            # this steps don't in this line 'commit false' 
            form_job= form.save(commit=False)
            # name field 'job'from model Job is only_job 
            form_job.job = only_job
            # save job 
            form_job.save()

    else:
        form = ApplyJob()
    context={
        "unique_job":only_job,
        "myform":form,


    }
    return render(request,"job/job_details.html",context )

job/templates/job/job_details.html
    
    {% extends "base.html" %}
    {% load bootstrap4 %}

    {% block body %}
 
  <!-- bradcam_area  -->
  <div class="bradcam_area bradcam_bg_1">
    <div class="container">
        <div class="row">
            <div class="col-xl-12">
                <div class="bradcam_text">
                    <h3>{{unique_job}}</h3>
                </div>
            </div>
        </div>
    </div>
</div>
<!--/ bradcam_area  -->

<div class="job_details_area">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="job_details_header">
                    <div class="single_jobs white-bg d-flex justify-content-between">
                        <div class="jobs_left d-flex align-items-center">
                            <div class="thumb">
                                <img src="img/svg_icon/1.svg" alt="">
                            </div>
                            <div class="jobs_conetent">
                                <a href="#"><h4>{{unique_job}}</h4></a>
                                <div class="links_locat d-flex align-items-center">
                                    <div class="location">
                                        <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                    </div>
                                    <div class="location">
                                        <p> <i class="fa fa-clock-o"></i> {{unique_job.job_type}}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="jobs_right">
                            <div class="apply_now">
                                <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="descript_wrap white-bg">
                    <div class="single_wrap">
                        <h4>Job description</h4>
                        <p>{{unique_job.descriptions}}</p>
                        {% comment %} <p>Variations of passages of lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p> {% endcomment %}
                    </div>
                    {% comment %} <div class="single_wrap">
                        <h4>Responsibility</h4>
                        <ul>
                            <li>The applicants should have experience in the following areas.
                            </li>
                            <li>Have sound knowledge of commercial activities.</li>
                            <li>Leadership, analytical, and problem-solving abilities.</li>
                            <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                        </ul>
                    </div>
                    <div class="single_wrap">
                        <h4>Qualifications</h4>
                        <ul>
                            <li>The applicants should have experience in the following areas.
                            </li>
                            <li>Have sound knowledge of commercial activities.</li>
                            <li>Leadership, analytical, and problem-solving abilities.</li>
                            <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>
                        </ul>
                    </div>
                    <div class="single_wrap">
                        <h4>Benefits</h4>
                        <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>
                    </div> {% endcomment %}
                </div>
                <div class="apply_job_form white-bg">
                    <h4>Apply for the job</h4>
                    {% comment %} bug : encrepting data form for validat and accept 'in view'  {% endcomment %}
                    <form method = "POST" enctype="multipart/form-data">
                        {% comment %} #set form dango from  model {% endcomment %}
                        {% csrf_token %}
                        {% bootstrap_form myform %}
                        {% buttons %}
                        
                          <button  class="boxed-btn3 w-100" type="submit">Apply Job</button>

                        {% endbuttons %}
                      
                  </form>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="job_sumary">
                    <div class="summery_header">
                        <h3>Job Summery</h3>
                    </div>
                    <div class="job_content">
                        <ul>
                            <li>Published on: <span>{{unique_job.published_add|date:"D d M Y" }} </span></li> 
                            {% comment %} {{ unique_job.published_add|time:"H:i" }} {% endcomment %}
                            <li>Vacancy: <span>{{unique_job.vacancy}}</span></li>
                            <li>Salary: <span>{{unique_job.salary}}</span></li>
                            <li>Location: <span>California, USA</span></li>
                            <li>Job Nature: <span> {{unique_job.job_type}}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="share_wrap d-flex">
                    <span>Share at:</span>
                    <ul>
                        <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                        <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                    </ul>
                </div>
                <div class="job_location_wrap">
                    <div class="job_lok_inner">
                        <div id="map" style="height: 200px;"></div>
                        <script>
                          function initMap() {
                            var uluru = {lat: -25.363, lng: 131.044};
                            var grayStyles = [
                              {
                                featureType: "all",
                                stylers: [
                                  { saturation: -90 },
                                  { lightness: 50 }
                                ]
                              },
                              {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                            ];
                            var map = new google.maps.Map(document.getElementById('map'), {
                              center: {lat: -31.197, lng: 150.744},
                              zoom: 9,
                              styles: grayStyles,
                              scrollwheel:  false
                            });
                          }
                          
                        </script>
                        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                        
                      </div>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- footer start -->

    {% endblock body %}

  

job/templates/job/job_list.html
    
    {% extends "base.html" %}
    {% block body %}
 

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{joblist.count }}+ Jobs Available</h3>
                        {% comment %} <h3>{{joblist | length }}+ Jobs Available</h3> {% endcomment %}
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    {% comment %} <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form action="#">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <input type="text" placeholder="Search keyword">
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Location">Location</option>
                                                <option value="1">Rangpur</option>
                                                <option value="2">Dhaka </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Category">Category</option>
                                                <option value="1">Category 1</option>
                                                <option value="2">Category 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Experience">Experience</option>
                                                <option value="1">Experience 1</option>
                                                <option value="2">Experience 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Job type">Job type</option>
                                                <option value="1">full time 1</option>
                                                <option value="2">part time 2 </option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Qualification">Qualification</option>
                                                <option value="1">Qualification 1</option>
                                                <option value="2">Qualification 2</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-12">
                                        <div class="single_field">
                                            <select class="wide">
                                                <option data-display="Gender">Gender</option>
                                                <option value="1">male</option>
                                                <option value="2">female</option>
                                            </select>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                        <div class="range_wrap">
                            <label for="amount">Price range:</label>
                            <div id="slider-range"></div>
                            <p>
                                <input type="text" id="amount" readonly style="border:0; color:#7A838B; font-size: 14px; font-weight:400;">
                            </p>
                        </div>
                        <div class="reset_btn">
                            <button  class="boxed-btn3 w-100" type="submit">Reset</button>
                        </div>
                    </div> {% endcomment %}
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                    <div class="serch_cat d-flex justify-content-end">
                                        <select>
                                            <option data-display="Most Recent">Most Recent</option>
                                            <option value="1">Marketer</option>
                                            <option value="2">Wordpress </option>
                                            <option value="4">Designer</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    
                    <div class="job_lists m-0">
                        <div class="row">
                            {% for j in joblist %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            {% comment %} <img src="{{j.image.url}}" alt=""> {% endcomment %}
                                            <img src="" alt="">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_details' j.slug %}"><h4>{{j}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i> California, USA</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{j.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'jobs:job_details' j.slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{j.published_add|date:"D d M Y" }} {{ j.published_add|time:"H:i" }}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        {% if joblist.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if joblist.has_previous %}
                                            <li><a href="?page={{ joblist.previous_page_number }}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}
                                        {% for j in  joblist.paginator.page_range %}
                                        <li><a href="?page={{j}}"><span>{{j}}</span></a></li>
                                        {% comment %} <li><a href="#"><span>02</span></a></li> {% endcomment %}
                                        {% endfor %}
                                        {% if  joblist.has_next %}
                                            <li><a href="?page={{ joblist.next_page_number }}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
    {% endblock %}